# Generated by Django 2.0.9 on 2018-11-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='song',
            name='illustration',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='song',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
