# Generated by Django 2.0.9 on 2018-12-30 14:56

import django.core.files.storage
from django.db import migrations, models
import romain_sings.songs.models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_auto_20181125_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/uploads', location='/Users/grfavre/Documents/Projets/romain_sings/romain_sings/media'), upload_to=romain_sings.songs.models.upload_to_sonos),
        ),
        migrations.AlterField(
            model_name='song',
            name='illustration',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media', location='/Users/grfavre/Documents/Projets/romain_sings/romain_sings/media'), upload_to=romain_sings.songs.models.qrcode_path),
        ),
        migrations.AlterField(
            model_name='song',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media', location='/Users/grfavre/Documents/Projets/romain_sings/romain_sings/media'), upload_to=romain_sings.songs.models.qrcode_path),
        ),
    ]
